version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-python
    restart: "no"
    ports:
      - "5555:5678"
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_EDITOR_BASE_URL=https://precious-relative-alpaca.ngrok-free.app
      - WEBHOOK_URL=https://precious-relative-alpaca.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - NODE_ENV=production
    volumes:
      - C:\Users\numan\n8n-files:/home/node/.n8n
    entrypoint: ["tini", "--", "/docker-entrypoint.sh"]
    user: "node"
    working_dir: /home/node
